# Generated by Django 3.2.5 on 2021-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
