# Generated by Django 3.2.5 on 2021-07-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, choices=[('Alfa Romeo ', 'Alfa Romeo'), ('Audi ', 'Audi'), ('bmw', 'bmw'), ('Citroen', 'Citroen'), ('Dacia ', 'Dacia'), ('Fiat ', 'Fiat'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jaguar ', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover ', 'Land Rover'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes'), ('Mitsubishi ', 'Mitsubishi'), ('Nissan ', 'Nissan'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Renault', 'Renault'), ('Skoda ', 'Skoda'), ('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('Vauxhall ', 'Vauxhall'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], help_text='optional', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, help_text='optional', max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.model'),
        ),
    ]
